MAIN:
  SEED: 42
  HEAD_DETECTION: False

DETECTING:
  SCORE_THRESHOLD: 0.75
  NMS_IOU_THRESHOLD: 0.2

TRACKING:
  STATE_NOISE: 1000.0
  R_SCALE: 5.0
  Q_VAR: 100.0
  IOU_THRESHOLD: 0.1
  MAX_AGE: 6
  MIN_HITS: 2

OUTPUT_VIDEO:
  CYCLE_LEN: 32
  BLOB_SIZE: 4
  LINE_WIDTH: 8
  FPS: 8
  MIN_AGE_FOR_TRAJECTORY: 12
  DRAW_BOX: True
